CREATE DATABASE BIBLIOTECA;
	
CREATE TABLE AUTOR (
	id INTEGER PRIMARY KEY NOT NULL,
	nome VARCHAR(100) NOT NULL ,
	nacionalidade VARCHAR(20) NOT NULL,
);

CREATE TABLE LIVRO(
	isbn INTEGER PRIMARY KEY NOT NULL,
	titulo VARCHAR (100) NOT NULL,
	ano_publicacao VARCHAR(100) NOT NULL,
	fk_editora INTEGER,
	fk_categoria INTEGER,
	FOREIGN KEY (fk_editora) REFERENCES EDITORA,
	FOREIGN KEY (fk_categoria) REFERENCES CATEGORIA
	);

CREATE TABLE LIVROAUTOR(
	id INTEGER PRIMARY KEY NOT NULL,
	fk_livro INTEGER,
	fk_autor INTEGER,
	FOREIGN KEY (fk_livro) REFERENCES LIVRO,
	FOREIGN KEY (fk_autor) REFERENCES AUTOR);

CREATE TABLE EDITORA(
	id INTEGER PRIMARY KEY NOT NULL,
	nome VARCHAR(100) NOT NULL ,
);

CREATE TABLE CATEGORIA(
	id INTEGER PRIMARY KEY NOT NULL,
	tipo_categoria VARCHAR(100) NOT NULL,
);